In [1]:
import numpy as np
def viterbi(pi,trans_matrix,emiss_matrix,string):
    # Pi is starting probability , we will assume all states are equally probable
    # trans_matrix is the transition matrix
    # emiss_matrix is emission matrix
    # string has all the observables
    no_of_states=np.shape(emiss_matrix)[0]
    string_length=np.shape(string)[0]
    # initiation of a blank path
    path=np.zeros(string_length,dtype=int)
    # viterbi matrix , contains the highest probability of any path that reaches a state i
    viterbi_matrix=np.zeros((no_of_states,string_length))
    # argmax matrix, that contains the argmax of each state , can be thought as a pointer matrix
    pointer_matrix=np.zeros((no_of_states,string_length))
    #initialization of pointer an dviterbi matrix
    viterbi_matrix[:,0]=pi*emiss_matrix[:,string[0]]
    pointer_matrix[:,0]=0
    # forward algorithm 
    for i in range(1,string_length):
        for j in range(no_of_states):
            viterbi_matrix[j,i]=np.max(viterbi_matrix[:,i-1]*trans_matrix[:,j])*emiss_matrix[j,string[i]]
            pointer_matrix[j,i]=np.argmax(viterbi_matrix[:,i-1]*trans_matrix[:,j])
    # using backtrack finding the best path
    path[string_length-1]=np.argmax(viterbi_matrix[:,string_length-1])
    for t in range(string_length-2,-1,-1):
        path[t]=pointer_matrix[path[t+1],t+1]
    return(path)

In [2]:
from random import choices
def hmm_gen(length,pi,trans_matrix,emiss_matrix):
    obs=np.arange(np.shape(emiss_matrix)[1],dtype=int)
    sta=np.arange(np.shape(emiss_matrix)[0],dtype=int)
    string=np.zeros(length,dtype=int)
    states=np.zeros(length,dtype=int)
    states[0]=choices(sta,pi)[0]
    string[0]=choices(obs,emiss_matrix[states[0]])[0]
    for i in range(1,length):
        states[i]=choices(sta,trans_matrix[states[i-1]])[0]
        string[i]=choices(obs,emiss_matrix[states[i]])[0]
    return string

In [3]:
pi=np.array([0.5,0.5])
t=np.array([[0.9,0.1],[0.2,0.8]])
e=np.array([[0.5,0.5],[0.3,0.7]])
l=400000

In [4]:
import time
%time s=hmm_gen(l,pi,t,e)

Wall time: 7.31 s


In [5]:
%time viterbi(pi,t,e,s)

Wall time: 23.5 s


array([0, 0, 0, ..., 0, 0, 0])

In [8]:
%time s1=hmm_gen(800000,pi,t,e)

Wall time: 15.3 s


In [9]:
%time viterbi(pi,t,e,s1)

Wall time: 45.9 s


array([0, 0, 0, ..., 0, 0, 0])

In [19]:
%time viterbi(pi,t,e,[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0])

Wall time: 7.43 ms


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])